-- AlterTable: Add PREVALIDATED and PREREJECTED to PhotoStatus enum
ALTER TABLE `Photo` MODIFY COLUMN `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'PREVALIDATED', 'PREREJECTED') NOT NULL DEFAULT 'PENDING';

-- AlterTable: Add PREVALIDATED and PREREJECTED to MediaStatus enum
ALTER TABLE `Media` MODIFY COLUMN `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'PREVALIDATED', 'PREREJECTED', 'DRAFT', 'IN_REVIEW', 'REVISION_REQUESTED', 'FINAL_APPROVED') NOT NULL DEFAULT 'PENDING';

-- AlterTable: Add PREVALIDATOR to TokenType enum
ALTER TABLE `ShareToken` MODIFY COLUMN `type` ENUM('VALIDATOR', 'MEDIA', 'PREVALIDATOR') NOT NULL;
